VEC-272 Add the ability to query
aerospike/asvec pull request #10
Opened 2024-08-23 22:52 UTC by jdogmcsteezy

Adds the following:

- Makes the client flags global. 
- Adds the following query commands

```
# Query using the zero vector displaying only fields name,age
asvec query -i my-index -n my-namespace -f name,age

# Query 10 vectors using an existing vector
asvec query -i my-index -n my-namespace -s my-set -k my-key --max-results 10

# Query using your own vector and change the displayed DATA column width to 100 characters.
asvec query -i my-index -n my-namespace -v "[1,0,1,0,0,0,1,0,1,1]" --max-width 100
```

2024-08-28 19:24 UTC, dwelch-spike requested changes
Content looks good. I mostly have nitpicks and suggestions.

2024-08-28 19:24 UTC, dwelch-spike commented on cmd/query.go
> +				}
IMO it would be nice to have this contained in a function like queryVectorByKey and trialAndErrorQuery

2024-08-28 19:24 UTC, dwelch-spike commented on cmd/writers/transformers.go
> +			ss[i] = removeFollowingZeros(fmt.Sprintf("%f", f))
Suggestion: `strconv.FormatFloat(f, 'f', -1, 32)` might get you what you want without the removeFollowingZeros function. Source: https://stackoverflow.com/questions/31289409/format-a-float-to-n-decimal-places-without-trailing-zeros

2024-08-28 22:55 UTC, jdogmcsteezy commented on cmd/flags/vector.go
> +	return "[]float32 or []int"
I want people to pass bools as [0,1,0,1,0,0]. We use a boolean in the client but
it is really meant to impliment a binary vector. 0,1 are integers . . . i figure
they will see the output in the `query` output which prints binary vectors as
[0,1,0,1,1]

Let me know if you have another suggestion but I think was we have it clearer.
People arn't going to want to type true,false,true,false

2024-08-28 22:55 UTC, jdogmcsteezy commented on cmd/flags/vector.go
> +func (v *VectorFlag) Set(val string) error {
added more comments

2024-08-28 22:57 UTC, jdogmcsteezy commented on cmd/indexCreate.go
> +	}
yes added comment

2024-08-28 23:01 UTC, jdogmcsteezy commented on cmd/query.go
> +	queryCmd.MarkFlagsMutuallyExclusive(flags.Vector, flags.KeyString)
nice, thank you. Should add tests for these

2024-08-28 23:30 UTC, jdogmcsteezy commented on cmd/flags/vector.go
> +func (v *VectorFlag) Set(val string) error {
also added some unit tests

2024-08-28 23:39 UTC, jdogmcsteezy commented on cmd/query.go
> +	queryCmd.MarkFlagsMutuallyExclusive(flags.Vector, flags.KeyString)
can actually be one line

2024-08-28 23:44 UTC, jdogmcsteezy commented on cmd/indexCreate.go
> +	}
also added some tests for this

2024-08-28 23:45 UTC, jdogmcsteezy commented on cmd/query.go
> +			logger.WarnContext(ctx, failedToRunVectorSearchErrMsg, slog.Any("error", err))
was trying to keep it the same level as the bool log level

2024-08-28 23:46 UTC, jdogmcsteezy commented on cmd/query.go
> +			if viper.IsSet(flags.Set) && !viper.IsSet(flags.KeyString) {
thanks

2024-08-28 23:49 UTC, jdogmcsteezy commented on cmd/query.go
> +	flagSet.UintVarP(&queryFlags.maxDataKeys, flags.MaxDataKeys, "m", defaultMaxDataKeys, "The maximum number of records to return.")
good catch. They are the same value so hard to catch

2024-08-28 23:52 UTC, jdogmcsteezy commented on cmd/query.go
> +	flagSet.VarP(&queryFlags.vector, flags.Vector, flags.VectorShort, "The vector to use as a query. Values true/false and 1/0 will result in a binary vector. Values containing a decimal will result in
There are examples in the cmd help. I'll add one more. I'd rather not make these
longer than needed

2024-08-28 23:53 UTC, jdogmcsteezy commented on cmd/query.go
> +				}
I also had that feeling. I'll see if I can do it while still liking how it it
turns out

2024-08-29 00:11 UTC, jdogmcsteezy commented on cmd/writers/transformers.go
> +			ss[i] = removeFollowingZeros(fmt.Sprintf("%f", f))
Tried. Now I remember that I need to manually do it so that I don't remove the
very last 0

2024-08-29 17:05 UTC, dwelch-spike commented on cmd/flags/vector.go
> +	return "[]float32 or []int"
this makes sense

2024-08-29 17:07 UTC, dwelch-spike commented on cmd/writers/transformers.go
> +			ss[i] = removeFollowingZeros(fmt.Sprintf("%f", f))
Ok, I wasn't sure exactly how it would look

2024-08-29 17:08 UTC, dwelch-spike approved these changes
LGTM

2024-08-29 17:16 UTC, merged